Task 1:
In this code, np.random.ranit generates a one dimensional array of size 10 ensuring that the upper bound of the array would less than 10.

In [7]:
import numpy as np

array = np.random.randint(10, size=10)
print(array)

[5 0 2 3 8 1 3 3 3 7]


Task2:
n this code, np.random.ranit generates a 7x6 dimensional array of size 10 ensuring that the upper bound of the array would less than 10.
Then I used the reshape function to reshape the array into 3x14 dimension

In [13]:
import numpy as np

print("7x6 array:")
array = np.random.randint(10 , size =(7, 6))
print(array)

print("3x14 array:")
reshaped_array = array.reshape(3,14)
print(reshaped_array)


7x6 array:
[[7 0 8 4 6 5]
 [8 2 3 9 7 5]
 [3 4 5 3 3 7]
 [9 9 9 7 3 2]
 [3 9 7 7 5 1]
 [2 2 8 1 5 8]
 [4 0 2 5 5 0]]
3x14 array:
[[7 0 8 4 6 5 8 2 3 9 7 5 3 4]
 [5 3 3 7 9 9 9 7 3 2 3 9 7 7]
 [5 1 2 2 8 1 5 8 4 0 2 5 5 0]]


Task 3:
In this task I iterated over the array and checked each of the elemnt if it is odd or not. After finding an odd element I appended it to the odd_numbers array


In [14]:
import numpy as np

array = np.array([0,1,2,3,4,5,6,7,8,9])

odd_numbers=[]

for num in array:
  if(num%2)!=0:
    odd_numbers.append(num)


print(np.array(odd_numbers))



[1 3 5 7 9]


Task 4:
In this task I iterated over the array and checked each of the elemnt if it is odd or not. After finding an odd element I replaced it with -1

In [17]:
import numpy as np

array = np.array([0,1,2,3,4,5,6,7,8,9])


for i in range(len(array)):
  if(array[i]%2)!=0 :
    array[i]=-1


print(array)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Task 5:
At first I copied the original array and then I iterated over the new out_array to perform the desired task.

In [22]:
import numpy as np

array = np.array([0,1,2,3,4,5,6,7,8,9])

out_array = np.copy(array)

for i in range(len(out_array)):
    if (out_array[i]%2) != 0:
        out_array[i] = -1

print("Original Array:")
print(array)
print("Replaced Array:")
print(out_array)


Original Array:
[0 1 2 3 4 5 6 7 8 9]
Replaced Array:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Task 6:
In this task I used the np.where function to find matched between a and b. After finding a match I appended the indices of the matched element to matching_positions array.

In [25]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
matching_positions=[]
matching_positions.append(np.where(a == b))
print(np.array(matching_positions))

[[[1 3 5 7]]]


Task 7:


In [27]:
import numpy as np

array = np.array([2, 6, 1, 9, 10, 3, 27])

out_array = array[(array >= 5) & (array <= 10)]

print(out_array)


[ 6  9 10]


Task 8:
In this task, I used ths np.concatenate to concatenate along both the axis

In [29]:
import numpy as np

# Creating a vector of size 10 with zeros
zeros = np.zeros(10)

# Creating a vector of size 10 with ones
ones = np.ones(10)

# Changing their dimension
reshaped_zeros = zeros.reshape(5, 2)
reshaped_ones = ones.reshape(5, 2)

# Merging vectors vertically
merge_vertically = np.concatenate((reshaped_zeros, reshaped_ones), axis=0)

# Merge vectors horizontally
merge_horizontally = np.concatenate((reshaped_zeros, reshaped_ones), axis=1)

print("Zeros Vector:")
print(zeros)

print("Ones Vector:")
print(ones)

print("Reshaped zero vector:")
print(reshaped_zeros)

print("Reshaped ones vector:")
print(reshaped_ones)

print("Merged Vertically:")
print(merge_vertically)

print("Merged Horizontally:")
print(merge_horizontally)


Zeros Vector:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones Vector:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Reshaped zero vector:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Reshaped ones vector:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Merged Vertically:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Merged Horizontally:
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


Task 9:
I used the ndarray function from numpy to create an ndarray

In [35]:
import numpy as np

x = np.ndarray(shape=(5,4), dtype=int, order='F')

print(x)

[[    100836652008320     139628639717616     139628639717616
      139628641026096]
 [                  0     139628641655152     139628640377120
      100813212116272]
 [    139628639717616     139628639717616     139628641026096
      139627368035024]
 [    139628639717616     139628639717616     139628641026096
  2913096084806529838]
 [    139628639717616     139628639717616     100813195430320
          43644120419]]


Task 10


In [36]:
import numpy as np
n_samples = 5
n_features = 4
x = np.random.rand(n_samples, n_features)
y = np.random.randint(0, 2, n_samples)
print(x)
print(y)

[[0.60825287 0.59665541 0.78364425 0.5000263 ]
 [0.05037006 0.69909807 0.9923964  0.26726254]
 [0.67909062 0.86428144 0.75084425 0.96448977]
 [0.55424244 0.2123905  0.22244322 0.21874937]
 [0.56957353 0.45210904 0.97023668 0.68054469]]
[1 1 0 0 1]


Task 11

In [41]:
def extract_subset(x, y, y0):
    # indices where y matches y0
    indices=[]
    indices.append(np.where(y == y0))

    # Extract subset of x based on indices
    subset_x = x[indices]

    return subset_x

import numpy as np
n_samples = 5
n_features = 4
x = np.random.rand(n_samples, n_features)
y = np.random.randint(0, 2, n_samples)
print(x)
print()
print(y)
print()
target_class=0
print(extract_subset(x, y, target_class))


[[0.36858461 0.13690027 0.82211773 0.18984791]
 [0.51131898 0.22431703 0.09784448 0.86219152]
 [0.97291949 0.96083466 0.9065555  0.77404733]
 [0.33314515 0.08110139 0.40724117 0.23223414]
 [0.13248763 0.05342718 0.72559436 0.01142746]]

[1 1 0 0 0]

[[[[0.97291949 0.96083466 0.9065555  0.77404733]
   [0.33314515 0.08110139 0.40724117 0.23223414]
   [0.13248763 0.05342718 0.72559436 0.01142746]]]]


Task 12


In [43]:
import pandas as pd
from urllib.request import urlopen

# URL of the Iris dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Define column names
column_names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]

# Load the dataset
iris_df = pd.read_csv(url, names=column_names)

# Print the DataFrame
print(iris_df)


     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


Task 13

In [44]:
import pandas as pd

# URL of the Iris dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Column names
column_names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]

# Load the dataset
iris_df = pd.read_csv(url, names=column_names)

# Calculate mean, median, and standard deviation of the 1st column (sepal length)
sepal_length_column = iris_df["sepal_length"]
mean_sepal_length = sepal_length_column.mean()
median_sepal_length = sepal_length_column.median()
std_sepal_length = sepal_length_column.std()

# Print mean, median, and standard deviation
print("Mean of sepal length:", mean_sepal_length)
print("Median of sepal length:", median_sepal_length)
print("Standard Deviation of sepal length:", std_sepal_length)

# Statistical summary
statistical_summary = iris_df.describe()
print("Statistical Summary:")
print(statistical_summary)


Mean of sepal length: 5.843333333333334
Median of sepal length: 5.8
Standard Deviation of sepal length: 0.828066127977863
Statistical Summary:
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
